# Site Settings
title: Willem Hekman
email: willem@willemhekman.nl
description: >
  Hey.
baseurl: ""
url: "http://whekman.github.io"
twitter_username: whekman
github_username:  whekman
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
